SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO `isocodes` (`code`, `country`, `cleaned`) VALUES
('AD', 'Andorra ', 1),
('AE', 'United Arab Emirates ', 0),
('AF', 'Afghanistan ', 0),
('AG', 'Antigua and Barbuda ', 0),
('AI', 'Anguilla ', 0),
('AL', 'Albania ', 0),
('AM', 'Armenia ', 0),
('AN', 'Netherlands Antilles ', 0),
('AO', 'Angola ', 0),
('AQ', 'Antarctica ', 0),
('AR', 'Argentina ', 0),
('AS', 'American Samoa ', 0),
('AT', 'Austria ', 0),
('AU', 'Australia ', 0),
('AW', 'Aruba ', 0),
('AX', 'Åland Islands ', 0),
('AZ', 'Azerbaijan ', 0),
('BA', 'Bosnia and Herzegovina ', 0),
('BB', 'Barbados ', 0),
('BD', 'Bangladesh ', 0),
('BE', 'Belgium ', 0),
('BF', 'Burkina Faso ', 0),
('BG', 'Bulgaria ', 0),
('BH', 'Bahrain ', 0),
('BI', 'Burundi ', 0),
('BJ', 'Benin ', 0),
('BM', 'Bermuda ', 0),
('BN', 'Brunei Darussalam ', 0),
('BO', 'Bolivia ', 0),
('BR', 'Brazil ', 0),
('BS', 'Bahamas ', 0),
('BT', 'Bhutan ', 0),
('BV', 'Bouvet Island ', 0),
('BW', 'Botswana ', 0),
('BY', 'Belarus ', 0),
('BZ', 'Belize ', 0),
('CA', 'Canada ', 0),
('CC', 'Cocos (Keeling) Islands ', 0),
('CD', 'Democratic Republic of the Congo', 0),
('CF', 'Central African Republic ', 0),
('CG', 'Republic of the Congo ', 0),
('CH', 'Switzerland ', 0),
('CI', 'Côte d''Ivoire ', 0),
('CK', 'Cook Islands ', 0),
('CL', 'Chile ', 0),
('CM', 'Cameroon ', 0),
('CN', 'China ', 0),
('CO', 'Colombia ', 0),
('CR', 'Costa Rica ', 0),
('CU', 'Cuba ', 0),
('CV', 'Cape Verde ', 0),
('CX', 'Christmas Island ', 0),
('CY', 'Cyprus ', 0),
('CZ', 'Czech Republic ', 0),
('DE', 'Germany ', 0),
('DJ', 'Djibouti ', 0),
('DK', 'Denmark ', 0),
('DM', 'Dominica ', 0),
('DO', 'Dominican Republic ', 0),
('DZ', 'Algeria ', 0),
('EC', 'Ecuador ', 0),
('EE', 'Estonia ', 0),
('EG', 'Egypt ', 0),
('EH', 'Western Sahara ', 0),
('ER', 'Eritrea ', 0),
('ES', 'Spain ', 0),
('ET', 'Ethiopia ', 0),
('FI', 'Finland ', 0),
('FJ', 'Fiji ', 0),
('FK', 'Falkland Islands (Malvinas) ', 0),
('FM', 'Federated States of Micronesia', 0),
('FO', 'Faroe Islands ', 0),
('FR', 'France ', 0),
('GA', 'Gabon ', 0),
('GB', 'United Kingdom ', 0),
('GD', 'Grenada ', 0),
('GE', 'Georgia ', 0),
('GF', 'French Guiana ', 0),
('GG', 'Guernsey ', 0),
('GH', 'Ghana ', 0),
('GI', 'Gibraltar ', 0),
('GL', 'Greenland ', 0),
('GM', 'Gambia ', 0),
('GN', 'Guinea ', 0),
('GP', 'Guadeloupe ', 0),
('GQ', 'Equatorial Guinea ', 0),
('GR', 'Greece ', 0),
('GS', 'South Georgia and the South Sandwich Islands ', 0),
('GT', 'Guatemala ', 0),
('GU', 'Guam ', 0),
('GW', 'Guinea-Bissau ', 0),
('GY', 'Guyana ', 0),
('HK', 'Hong Kong ', 0),
('HM', 'Heard Island and McDonald Islands ', 0),
('HN', 'Honduras ', 0),
('HR', 'Croatia ', 0),
('HT', 'Haiti ', 0),
('HU', 'Hungary ', 0),
('ID', 'Indonesia ', 0),
('IE', 'Ireland ', 0),
('IL', 'Israel ', 0),
('IM', 'Isle of Man ', 0),
('IN', 'India ', 0),
('IO', 'British Indian Ocean Territory ', 0),
('IQ', 'Iraq ', 0),
('IR', 'Islamic Republic of Iran', 0),
('IS', 'Iceland ', 0),
('IT', 'Italy ', 0),
('JE', 'Jersey ', 0),
('JM', 'Jamaica ', 0),
('JO', 'Jordan ', 0),
('JP', 'Japan ', 0),
('KE', 'Kenya ', 0),
('KG', 'Kyrgyzstan ', 0),
('KH', 'Cambodia ', 0),
('KI', 'Kiribati ', 0),
('KM', 'Comoros ', 0),
('KN', 'Saint Kitts and Nevis ', 0),
('KP', 'Democratic People''s Republic of Korea', 0),
('KR', 'Republic of Korea', 0),
('KW', 'Kuwait ', 0),
('KY', 'Cayman Islands ', 0),
('KZ', 'Kazakhstan ', 0),
('LA', 'Lao People''s Democratic Republic ', 0),
('LB', 'Lebanon ', 0),
('LC', 'Saint Lucia ', 0),
('LI', 'Liechtenstein ', 0),
('LK', 'Sri Lanka ', 0),
('LR', 'Liberia ', 0),
('LS', 'Lesotho ', 0),
('LT', 'Lithuania ', 0),
('LU', 'Luxembourg ', 0),
('LV', 'Latvia ', 0),
('LY', 'Libyan Arab Jamahiriya ', 0),
('MA', 'Morocco ', 0),
('MC', 'Monaco ', 0),
('MD', 'Republic of Moldova', 0),
('ME', 'Montenegro ', 0),
('MG', 'Madagascar ', 0),
('MH', 'Marshall Islands ', 0),
('MK', 'Macedonia', 0),
('ML', 'Mali ', 0),
('MM', 'Myanmar ', 0),
('MN', 'Mongolia ', 0),
('MO', 'Macao ', 0),
('MP', 'Northern Mariana Islands ', 0),
('MQ', 'Martinique ', 0),
('MR', 'Mauritania ', 0),
('MS', 'Montserrat ', 0),
('MT', 'Malta ', 0),
('MU', 'Mauritius ', 0),
('MV', 'Maldives ', 0),
('MW', 'Malawi ', 0),
('MX', 'Mexico ', 0),
('MY', 'Malaysia ', 0),
('MZ', 'Mozambique ', 0),
('NA', 'Namibia ', 0),
('NC', 'New Caledonia ', 0),
('NE', 'Niger ', 0),
('NF', 'Norfolk Island ', 0),
('NG', 'Nigeria ', 0),
('NI', 'Nicaragua ', 0),
('NL', 'Netherlands ', 0),
('NO', 'Norway ', 0),
('NP', 'Nepal ', 0),
('NR', 'Nauru ', 0),
('NU', 'Niue ', 0),
('NZ', 'New Zealand ', 0),
('OM', 'Oman ', 0),
('PA', 'Panama ', 0),
('PE', 'Peru ', 0),
('PF', 'French Polynesia ', 0),
('PG', 'Papua New Guinea ', 0),
('PH', 'Philippines ', 0),
('PK', 'Pakistan ', 0),
('PL', 'Poland ', 0),
('PM', 'Saint Pierre and Miquelon ', 0),
('PN', 'Pitcairn ', 0),
('PR', 'Puerto Rico ', 0),
('PS', 'Palestinian Territory', 0),
('PT', 'Portugal ', 0),
('PW', 'Palau ', 0),
('PY', 'Paraguay ', 0),
('QA', 'Qatar ', 0),
('RE', 'Réunion ', 0),
('RO', 'Romania ', 0),
('RS', 'Serbia ', 0),
('RU', 'Russian Federation ', 0),
('RW', 'Rwanda ', 0),
('SA', 'Saudi Arabia ', 0),
('SB', 'Solomon Islands ', 0),
('SC', 'Seychelles ', 0),
('SD', 'Sudan ', 0),
('SE', 'Sweden ', 0),
('SG', 'Singapore ', 0),
('SH', 'Saint Helena ', 0),
('SI', 'Slovenia ', 0),
('SJ', 'Svalbard and Jan Mayen ', 0),
('SK', 'Slovakia ', 0),
('SL', 'Sierra Leone ', 0),
('SM', 'San Marino ', 0),
('SN', 'Senegal ', 0),
('SO', 'Somalia ', 0),
('SR', 'Suriname ', 0),
('ST', 'Sao Tome and Principe ', 0),
('SV', 'El Salvador ', 0),
('SY', 'Syrian Arab Republic ', 0),
('SZ', 'Swaziland ', 0),
('TC', 'Turks and Caicos Islands ', 0),
('TD', 'Chad ', 0),
('TF', 'French Southern Territories ', 0),
('TG', 'Togo ', 0),
('TH', 'Thailand ', 0),
('TJ', 'Tajikistan ', 0),
('TK', 'Tokelau ', 0),
('TL', 'Timor-Leste ', 0),
('TM', 'Turkmenistan ', 0),
('TN', 'Tunisia ', 0),
('TO', 'Tonga ', 0),
('TR', 'Turkey ', 0),
('TT', 'Trinidad and Tobago ', 0),
('TV', 'Tuvalu ', 0),
('TW', 'Taiwan', 0),
('TZ', 'Tanzania', 0),
('UA', 'Ukraine ', 0),
('UG', 'Uganda ', 0),
('UM', 'United States Minor Outlying Islands ', 0),
('US', 'United States ', 0),
('UY', 'Uruguay ', 0),
('UZ', 'Uzbekistan ', 0),
('VA', 'Holy See (Vatican City State) ', 0),
('VC', 'Saint Vincent and the Grenadines ', 0),
('VE', 'Venezuela ', 0),
('VG', 'British Virgin Islands', 0),
('VI', 'U.S. Virgin Islands', 0),
('VN', 'Vietnam', 0),
('VU', 'Vanuatu ', 0),
('WF', 'Wallis and Futuna ', 0),
('WS', 'Samoa ', 0),
('YE', 'Yemen ', 0),
('YT', 'Mayotte ', 0),
('ZA', 'South Africa ', 0),
('ZM', 'Zambia ', 0),
('ZW', 'Zimbabwe ', 0),
('KV', 'Kosovo', 0),
('un', 'United Nations', 0);
